services:
  frontend:
    build:
      context: ./albums
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./albums:/app:rw
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]

  backend:
    build:
      context: ./albums-be
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./albums-be:/app:rw
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
